### ISSUE TITLE
Component or plugin aliyun_vpc is not found

### ISSUE THREAD

**Issue by mogu1986** [devsapp/aliyun-resources#1]
**代码如下：**

```yaml
resources:
  xl_test_vpc_1: 
    component: aliyun_vpc
    props:
      vpc_name: xl-test-vpc
      cidr_block: 172.16.0.0/12
      secondary_cidr_blocks:
        - 172.16.0.0/12
      description: a test vpc

  ros-res:
    component: ros-transformer
    props:
      region: ${vars.region}
      name: test
      ref:
        xl_test_vpc_1: ${resources.xl_test_vpc_1.output.resource}   
```

**执行 s deploy -y 时报错：**
```shell
Error Message:
Component or plugin aliyun_vpc is not found
 
A complete log of this run can be found in: /Users/xiaoxiao/.s/logs/0417163556
 
Env:       @serverless-devs/s: 3.0.7, darwin-x64 node-v14.21.3                                   
Logs:      /Users/xiaoxiao/.s/logs/0417163556                                                    
Feedback:  https://github.com/Serverless-Devs/Serverless-Devs/issues 
```

这个插件不是自动安装的吗，该如何安装？
